### ISSUE TITLE
Implement DROP database functionality

### ISSUE THREAD

**Issue by jmsuhy** [DozerDB/dozerdb-core#1]
Databases can be created now - but the drop database functionality is not implemented yet.  We want to implement the DROP database functionality for the first 1.0 release.

**Comment by alextsakpinis** [comment]
Are there any news on when the DROP database functionality may be released? Thanks a lot for your work!

**Comment by jmsuhy** [comment]
Sorry for the late reply - we've been organizing the teams and governance process to be able to effectively get the community involved more.    We have it working already locally and just need to generate some tests for it.   Right now, when you DROP a database, it does not make a backup for you incase you change your mind.  DROP is final.

I expect we are going to merge that and 2 other big tickets in the next week or 2.

**Comment by alextsakpinis** [comment]
These are great news. Thanks for letting me know!

**Comment by nifets-ai** [comment]
Hi, wondering if there are any updates on this, or a timeline for when this feature will be available?

**Comment by rg2609** [comment]
Hey there, just confirming that this feature is completed!

**Comment by jmsuhy** [comment]
Not yet - we have not created the tests yet but have a working version.   I will close this ticket once it is merged. 
As the team grows, we should be able to tackle these much faster!

**Comment by Bligoubloups** [comment]
Hi!
Is there a manual way to delete a database?
I tried deleting some folders, but I couldn't remove everything related to it.
Thanks

**Comment by Abutler101** [comment]
> Hi! Is there a manual way to delete a database? I tried deleting some folders, but I couldn't remove everything related to it. Thanks

I'm pretty sure there's some files in the `system` Database that list the dbs and some index info, edits to these could be the final step, but last I tried I just corrupted the entire Neo4j instance😅. I'll take a look back into it

**Comment by Zeppier** [comment]
@jmsuhy Hey! Are there any updates on this? Can I help somehow with it?

**Comment by jmsuhy** [comment]
If you manually delete the files there will be issues as the system database will still have a record of it.

I will try to finish the feature personally ASAP.

**Comment by Johnno1011** [comment]
Hey guys, are there any updates on this? I was checking out this project the other day and would love to migrate my DBs across, however deleting databases is something that I'd need as a requirement 😄 So a script to delete the DB folder would break things?

**Comment by jmsuhy** [comment]
Yes - I was able to work on this over the weekend. I have it functioning now locally. I will push up an update then after a quick code review , we will build the newest version with the functional DROP database functionality.

**Comment by Johnno1011** [comment]
Thanks @jmsuhy, I'd love to build the docker image for this development branch myself - any chance you could please point me in the direction of the Dockerfile or if not published, share it? 😄 
Many thanks !

**Comment by jmsuhy** [comment]
We will push a new repository for the Docker build along with instructions. We’ve been using https://github.com/neo4j/docker-neo4j-publish as a base, pointing to our packaged distribution. Someone from the team or I will set that up for you soon.

**Comment by Zeppier** [comment]
@jmsuhy Hey, I see that the version was updated and now includes the commit for DROP DATABASE functionality. However, I tried that image and I still got "Unsupported administration command: DROP DATABASE test". Do you have any suggestions for what I did wrong? The image I used is graphstack/dozerdb:5.24.2.0-alpha.1

**Comment by jmsuhy** [comment]
We are going to push up a new image - most likely this week - it will be 5.24.2.1 - and will have the ability to drop, start and stop databases.

**Comment by Zeppier** [comment]
@jmsuhy Thanks! Sounds fantastic!

**Comment by jmsuhy** [comment]
Added the ability to stop, start and drop databases.  Dist was pushed to dozerdb.org
