### ISSUE TITLE
Implement STOP and START functionality for databases

### ISSUE THREAD

**Issue by jmsuhy** [DozerDB/dozerdb-core#10]
Implement STOP DATABASE <database-name> and START DATABASE <database-name>.

Currently, all databases are started when the server is started.

**Comment by awhillas** [comment]
I take it this means that all the DBs are in memory all the time? 
I guess what would be ideal would to have the last N accesses databases in memory and the rest stopped? 
Or at least a way that this could be managed externally via API? I assume there is a way to track memory consumption and/or get the size of a DB before one loads it into memory? Something like Kubernetes would scale if the memory went up but this doesn't scale horizontally, does it?
Sorry for all the questions...

**Comment by jmsuhy** [comment]
With the multi-database feature, not all databases are automatically loaded into memory.   The core of this functionality is in Neo4j Core, we just build out the parts that were only implemented in enterprise.  I believe Neo4j core uses a demand-based loading mechanism, which means databases are only loaded into memory when they are started and accessed.     I.E.  If you start up a bunch of databases but don't access them or do hot loading, then you won't be loading them all into memory.
 
 I need to validate this statement - but I believe it is correct.

**Comment by Imbalanceone** [comment]
is there any progress on this issue?  i want use neo4j-admin database import, for updating some databases without turn off all neo4j, because all databases are lock.

**Comment by jmsuhy** [comment]
This is the next task on our list.   We just pushed the drop database functionality, and we’re trying to complete this task as well.

**Comment by jmsuhy** [comment]
Added the ability to stop and start databases.
