### ISSUE TITLE
Production use case

### ISSUE THREAD

**Issue by kushankurdas** [DozerDB/dozerdb-core#23]
We have a use case for graph database in production for enterprise customers, we wanted to know if we can use this as a self managed in our servers. We have couple of questions regarding our use cases and support. Please connect with us so we can take the conversation from there. Dropping my email id for reference kushankur@scrut.io

**Comment by jmsuhy** [comment]
Sure, I will reach out.    Regarding using in production.  Of course you can.   Neo4j and the Plugin are both GPLv3 and have no limitation on production usage, etc.

I am closing this ticket and reaching out via email.
