### ISSUE TITLE
Upgrade to Neo4j Core 5.24.2

### ISSUE THREAD

**Issue by pippascroggins** [DozerDB/dozerdb-core#24]
Upgrade to newest Neo4j core 5.23.0.

**Comment by jmsuhy** [comment]
We are jumping to 5.24.0.

**Comment by f1-outsourcing** [comment]
Is it possible we can do this ourselves or is it quite a bit of work patching for a new version?

**Comment by jmsuhy** [comment]
You can definitely create versions yourself - in fact, one of our internal tasks is to create the documentation showing the community how to build everything end-to-end.

**Comment by jmsuhy** [comment]
Looks like Neo4j may have had some issues with 5.24.0 - 5.24.1 was just pushed - so we will use that.

**Comment by f1-outsourcing** [comment]
@jmsuhy  How is it going? :)

**Comment by alexanoid** [comment]
Does DozerDB support block storage and PARALLEL runtime like Neo4j EE?

**Comment by jmsuhy** [comment]
Our current focus is on implementing enterprise-grade features such as security and advanced capabilities. If Neo4j introduces performance constraints in the Community Edition through storage or runtime changes, we will address those limitations through enhancements in our plugin.

As the community and our team grows , we are going to start having the community vote on features such as this.

**Comment by jmsuhy** [comment]
Neo4j just pushed another patch 5.25.2 - this seems to be a common scenario with them lately.

**Comment by f1-outsourcing** [comment]
Where should we get this, here from this list, not?
https://dozerdb.org/

**Comment by jmsuhy** [comment]
We have not released the 5.25.2 version yet -  but I expect it to be done by this weekend.

**Comment by alexanoid** [comment]
@jmsuhy Thank you for your response. Where can I find a list of all the features that DozerDB currently adds to Neo4j CE?

**Comment by jmsuhy** [comment]
5.24.2 Version has been pushed live.   As for the list of features, look at the bottom of https://dozerdb.org under Roadmap.
You will see the features already in place with green checks next to them.

**Comment by f1-outsourcing** [comment]
Nice! Just trying it, is this related to you or the neo4j update. I have never (in the 2 - 3 weeks I am using it ;)) seen this printed to the console

```
HTTP/1.1 200
Date: Thu, 17 Oct 2024 20:10:11 GMT
Access-Control-Allow-Origin: *
Cache-Control: no-store
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' cdn.segment.com canny.io; img-src 'self' guides.neo4j.com data:; style-src 'self' fonts.googleapis.com 'unsafe-inline'; font-src 'self' fonts.gstatic.com; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; connect-src 'self' api.canny.io api.segment.io ws: wss: http: https:
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

```

I was also trying to clean up some mess I created by dropping some empty databases, but I get this error.

`Unsupported administration command: drop database moviedb`

Do I need to configure something in neo4j.conf? I see the Dozer name in the web browser so looks like this install was ok.

**Comment by jmsuhy** [comment]
We notices those new logs too.  They started with this Neo4j version.   

I am assuming you would see same thing in vanilla Neo4j Community 5.24.2 as well.

We are going to implement the DROP Database among a few other multi db admin commands soon.

**Comment by f1-outsourcing** [comment]
> We notices those new logs too. They started with this Neo4j version.
> 
> I am assuming you would see same thing in vanilla Neo4j Community 5.24.2 as well.
> 
> We are going to implement the DROP Database among a few other multi db admin commands soon.

Yes did everything the same version. I thought I had some filesystem permissions to strict so I was creating even more empty databases. :)
