### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by kaumudpa** [DozerDB/dozerdb-core#4]
Unable to install this image on AWS ARM based instances. Please see if this can be incorporated as official Neo4J Community Edition runs perfectly fine there.

**Comment by jmsuhy** [comment]
We only built the x86 images, but we can also create the ARM images as well.   I will create the ARM image for 5.15.0 and push it to docker hub.

Moving forward we will publish both images for each release.

If you want an ARM image for an older release, just let us know.

**Comment by kaumudpa** [comment]
Hi Thank you for the reply - I think ARM image for 5.15.0 should be fine for now.

But I would like to suggest publishing both images for each release henceforth as it broadens the scope for testing.

Any yes - kudos to the work done here!

**Comment by kaumudpa** [comment]
@jmsuhy 
Any ETA to push ARM image for 5.15.0?

**Comment by jmsuhy** [comment]
It should be pushed by tomorrow at the latest.

**Comment by jmsuhy** [comment]
FYI - the proper manifests were pushed to docker hub - you should be able to run the image on x86 and arm processors now.  
You can remove the old image using docker image rm graphstack/dozerdb:5.15.0.0-alpha.1

Then try to run again.

Can you confirm if all works?   

 docker run \
            -p7474:7474 -p7687:7687 \
            -v $HOME/neo4j/data:/data \
            -v $HOME/neo4j/logs:/logs \
            -v $HOME/neo4j/import:/var/lib/neo4j/import \
            -v $HOME/neo4j/plugins:/plugins \
            --env NEO4J_AUTH=neo4j/password \
            graphstack/dozerdb:5.15.0.0-alpha.1

**Comment by jmsuhy** [comment]
Also - dozerdb 5.16.0.0-alpha.1 has been pushed which is DozerDB plugin and Neo4j Core 5.16.0
The arm compatible versions are DozerDB instance for Neo4j 5.15.0 and 5.16.0.  If you need an ARM docker image for another version of 5.x - please let us know.

**Comment by kaumudpa** [comment]
I can confirm - This is working fine on ARM instances - Closing this issue.
