### ISSUE TITLE
Migration form Neo4j 3.5 to 5.16

### ISSUE THREAD

**Issue by janakmistry** [DozerDB/dozerdb-core#7]
We are looking to transition from Neo4j version 3.5 to 5.16.
In our search for migration guidance, we came across a post at [https://community.neo4j.com/t/migration-issue-from-3-5-to-4-x-store-format-upgrade-from-v0-a-8/61793/7 ](https://community.neo4j.com/t/migration-issue-from-3-5-to-4-x-store-format-upgrade-from-v0-a-8/61793/7). 
According to the information provided in the post, the recommended approach is to first migrate from version 3.5 to 4.X and then proceed to migrate to 5.X. 

This migration is essential as we plan to utilize dozerdb:5.16.0.0-alpha.1

Any assistance or guidance you can provide for this migration process would be greatly appreciated.

**Comment by jmsuhy** [comment]
Yes - if you are going to upgrade the stores you would follow the upgrade instructions to upgrade from 3.5 to 4.x, then you can upgrade to 5.x.    You could also just use apoc to export and import, but its quite easy to upgrade manually too.  Remember to set your neo4j.conf setting to allow for upgrade (which is in the neo4j docs).

We upgraded a 2TB 3.5.x graph in that manner, and it took about an hour or so.   Make sure to backup your data directories too.

**Comment by jmsuhy** [comment]
If this answered your question, please close the ticket, otherwise let us know if the response was helpful.  
Thank you.

**Comment by janakmistry** [comment]
Thanks for the suggestion. It works.
